# Generated by Django 2.0.8 on 2018-10-08 18:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('menu', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created',
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name='created',
                    ),
                ),
                (
                    'modified',
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name='modified',
                    ),
                ),
                (
                    'uuid',
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                (
                    'products',
                    models.ManyToManyField(
                        blank=True,
                        related_name='dishes',
                        to='products.Product',
                        verbose_name='Products',
                    ),
                ),
            ],
            options={'verbose_name': 'Dish', 'verbose_name_plural': 'Dishes'},
        ),
        migrations.CreateModel(
            name='DishItem',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created',
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name='created',
                    ),
                ),
                (
                    'modified',
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name='modified',
                    ),
                ),
                (
                    'uuid',
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    'period',
                    models.IntegerField(
                        choices=[
                            (0, 'Breakfast'),
                            (1, 'Lunch'),
                            (2, 'Tea'),
                            (3, 'Dinner'),
                        ],
                        verbose_name='Period',
                    ),
                ),
                (
                    'dishes',
                    models.ManyToManyField(
                        blank=True,
                        related_name='dish_items',
                        to='dishes.Dish',
                        verbose_name='Dishes',
                    ),
                ),
                (
                    'menu_day',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='dish_items',
                        to='menu.MenuDay',
                        verbose_name='Menu day',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Dish item',
                'verbose_name_plural': 'Set of dishes',
            },
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created',
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name='created',
                    ),
                ),
                (
                    'modified',
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name='modified',
                    ),
                ),
                (
                    'uuid',
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ('value', models.CharField(max_length=20, verbose_name='Value')),
                (
                    'age_category',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='outputs',
                        to='common.AgeCategory',
                        verbose_name='Age category',
                    ),
                ),
                (
                    'dish',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='outputs',
                        to='dishes.Dish',
                        verbose_name='Dish',
                    ),
                ),
                (
                    'group',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='outputs',
                        to='common.Group',
                        verbose_name='Group',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Output value',
                'verbose_name_plural': 'Output values',
            },
        ),
    ]
