# Generated by Django 2.0.8 on 2018-11-02 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishitem',
            name='dishes',
        ),
        migrations.RemoveField(
            model_name='dishitem',
            name='menu_day',
        ),
        migrations.DeleteModel(
            name='DishItem',
        ),
    ]
