# Generated by Django 2.0.8 on 2019-04-22 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0002_auto_20190228_1455'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ['name'], 'verbose_name': 'Dish', 'verbose_name_plural': 'Dishes'},
        ),
    ]
