# Generated by Django 2.0.8 on 2019-01-02 20:49

from decimal import Decimal
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('item_number', models.CharField(max_length=100, unique=True, verbose_name='Item number')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('unit', models.IntegerField(choices=[(0, 'Kg'), (1, 'Pcs'), (2, 'Jar'), (3, 'Liter')], verbose_name='Unit')),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Unit price')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['item_number'],
            },
        ),
    ]
