# Generated by Django 2.0.8 on 2018-10-08 18:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [('common', '0001_initial')]

    operations = [
        migrations.CreateModel(
            name='Norm',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created',
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name='created',
                    ),
                ),
                (
                    'modified',
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name='modified',
                    ),
                ),
                (
                    'uuid',
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ('value', models.IntegerField(verbose_name='Value')),
                (
                    'age_category',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='norms',
                        to='common.AgeCategory',
                        verbose_name='Age category',
                    ),
                ),
                (
                    'group',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='norms',
                        to='common.Group',
                        verbose_name='Group',
                    ),
                ),
            ],
            options={'verbose_name': 'Norm', 'verbose_name_plural': 'Norms'},
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created',
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name='created',
                    ),
                ),
                (
                    'modified',
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name='modified',
                    ),
                ),
                (
                    'uuid',
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    'item_number',
                    models.CharField(
                        max_length=100, unique=True, verbose_name='Item number'
                    ),
                ),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                (
                    'unit',
                    models.IntegerField(
                        choices=[(0, 'Kg'), (1, 'Pcs'), (2, 'Jar'), (3, 'Liter')],
                        verbose_name='Unit',
                    ),
                ),
                (
                    'unit_price',
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name='Unit price'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['item_number'],
            },
        ),
        migrations.AddField(
            model_name='norm',
            name='product',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='norms',
                to='products.Product',
                verbose_name='Product',
            ),
        ),
    ]
