# Generated by Django 2.0.8 on 2019-04-07 15:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190305_2232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='norm',
            options={'verbose_name': 'Norm', 'verbose_name_plural': 'Norms'},
        ),
        migrations.AlterField(
            model_name='norm',
            name='value',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=10, verbose_name='Value'),
        ),
    ]
