# Generated by Django 2.0.8 on 2019-08-13 19:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190407_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='convert_ratio',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, verbose_name='Convert ratio'),
        ),
    ]
