# Generated by Django 2.0.8 on 2019-02-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_dishtype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agecategory',
            options={'ordering': ['sort', 'name'], 'verbose_name': 'Age category', 'verbose_name_plural': 'Age categories'},
        ),
        migrations.AlterModelOptions(
            name='dishtype',
            options={'ordering': ['sort', 'name'], 'verbose_name': 'Dish type', 'verbose_name_plural': 'Dish types'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['sort', 'name'], 'verbose_name': 'Group', 'verbose_name_plural': 'Groups'},
        ),
        migrations.AddField(
            model_name='agecategory',
            name='sort',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sort'),
        ),
        migrations.AddField(
            model_name='dishtype',
            name='sort',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sort'),
        ),
        migrations.AddField(
            model_name='group',
            name='sort',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sort'),
        ),
    ]
