# Generated by Django 2.0.8 on 2019-04-22 15:51

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_productcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('director_initials', models.CharField(max_length=255, verbose_name='Director initials')),
                ('nurse_post', models.CharField(max_length=255, verbose_name='Nurse post')),
                ('nurse_initials', models.CharField(max_length=255, verbose_name='Nurse initials')),
                ('senior_nurse_post', models.CharField(max_length=255, verbose_name='Senior nurse post')),
                ('senior_nurse_initials', models.CharField(max_length=255, verbose_name='Senior nurse initials')),
                ('storekeeper_initials', models.CharField(max_length=255, verbose_name='Storekeeper initials')),
            ],
            options={
                'verbose_name': 'Default Settings',
            },
        ),
    ]
