# Generated by Django 2.0.8 on 2019-05-06 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_defaultsettings'),
        ('common', '0005_group_age_categories'),
    ]

    operations = [
    ]
