# Generated by Django 2.0.8 on 2019-05-12 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_merge_20190506_2250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defaultsettings',
            options={'verbose_name': 'Default Settings', 'verbose_name_plural': 'Default Settings'},
        ),
    ]
