# Generated by Django 2.2.5 on 2023-01-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_auto_20190512_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultsettings',
            name='cook_initials',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cook initials'),
        ),
    ]
