# Generated by Django 2.0.8 on 2019-02-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_logged_users',
            field=models.BooleanField(default=False, verbose_name='Can show logged users'),
        ),
    ]
