# Generated by Django 2.0.8 on 2018-11-02 13:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0002_auto_20181102_1537'),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('period', models.IntegerField(choices=[(0, 'Breakfast'), (1, 'Lunch'), (2, 'Tea'), (3, 'Dinner')], verbose_name='Period')),
                ('dishes', models.ManyToManyField(blank=True, related_name='dish_items', to='dishes.Dish', verbose_name='Dishes')),
            ],
            options={
                'verbose_name': 'Dish item',
                'verbose_name_plural': 'Set of dishes',
            },
        ),
        migrations.AlterField(
            model_name='menuday',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='menuday',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='draft', max_length=100, no_check_for_status=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='dishitem',
            name='menu_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dish_items', to='menu.MenuDay', verbose_name='Menu day'),
        ),
    ]
