# Generated by Django 2.0.8 on 2019-03-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishitem',
            name='period',
            field=models.IntegerField(choices=[(0, 'Breakfast'), (1, 'Lunch'), (2, 'Afternoon Snack'), (3, 'Dinner'), (4, 'Tea')], verbose_name='Period'),
        ),
    ]
