# Generated by Django 2.0.8 on 2019-04-22 15:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20190313_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuday',
            name='settings',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Settings'),
        ),
    ]
