# Generated by Django 2.0.8 on 2019-05-06 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_menuday_settings'),
        ('menu', '0003_auto_20190408_1931'),
    ]

    operations = [
    ]
