# Generated by Django 2.0.8 on 2019-05-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_merge_20190506_2250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuday',
            options={'ordering': ['-date'], 'verbose_name': 'Menu day', 'verbose_name_plural': 'Menu days'},
        ),
        migrations.AlterField(
            model_name='numberofpersons',
            name='value',
            field=models.IntegerField(blank=True, default=0, help_text='A total number of persons / A number of persons as day stay', verbose_name='Value'),
        ),
    ]
