# Generated by Django 2.2.5 on 2021-01-28 17:49

from django.db import migrations, models


def update_period_in_dish_items(apps, schema_editor):
    DishItem = apps.get_model("menu", "DishItem")

    dish_items = DishItem.objects.all()
    for dish_item in dish_items:
        if dish_item.period == 1:
            dish_item.period = 2
        elif dish_item.period == 2:
            dish_item.period = 3
        elif dish_item.period == 3:
            dish_item.period = 4
        elif dish_item.period == 4:
            dish_item.period = 5
        dish_item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20190512_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishitem',
            name='period',
            field=models.IntegerField(choices=[(0, 'Breakfast'), (1, '10:35 / 11:00'), (2, 'Lunch'), (3, '15:00 / 15:45'), (4, 'Dinner'), (5, 'Tea')], verbose_name='Period'),
        ),
        migrations.RunPython(
            update_period_in_dish_items,
        ),
    ]
