# Generated by Django 2.2.5 on 2023-01-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_auto_20210128_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishitem',
            name='period',
            field=models.IntegerField(choices=[(0, 'Breakfast'), (1, '10:00'), (2, 'Lunch'), (3, '15:00 / 15:45'), (4, 'Dinner'), (5, 'Tea')], verbose_name='Period'),
        ),
    ]
